# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='first_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users_who_favorited',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
