# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20191018_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
