# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20191018_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
