# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20191018_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plan',
            field=models.CharField(max_length=255),
        ),
    ]
