# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20191018_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
    ]
