# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20191018_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default='default'),
            preserve_default=False,
        ),
    ]
