# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0002_auto_20191011_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='author', to='book_authors_app.Book'),
        ),
    ]
