# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0003_auto_20191011_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes are Fun!!'),
            preserve_default=False,
        ),
    ]
