# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0004_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='book_authors_app.Book'),
        ),
    ]
