# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-14 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0005_auto_20191011_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='books',
        ),
    ]
