# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_ninjas_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='add a description'),
            preserve_default=False,
        ),
    ]
